name: hvac-llm-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - joblib
  - mlflow
  - pip:
      - azureml-mlflow
      - openai
      - python-dotenv
